// Generated by gencpp from file navigation_runner/GetPolicyInferenceRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCEREQUEST_H
#define NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_runner
{
template <class ContainerAllocator>
struct GetPolicyInferenceRequest_
{
  typedef GetPolicyInferenceRequest_<ContainerAllocator> Type;

  GetPolicyInferenceRequest_()
    : state()
    , state_shape()
    , lidar()
    , lidar_shape()
    , direction()
    , direction_shape()
    , dynamic_obstacle()
    , dynamic_obstacle_shape()  {
    }
  GetPolicyInferenceRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , state_shape(_alloc)
    , lidar(_alloc)
    , lidar_shape(_alloc)
    , direction(_alloc)
    , direction_shape(_alloc)
    , dynamic_obstacle(_alloc)
    , dynamic_obstacle_shape(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _state_type;
  _state_type state;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _state_shape_type;
  _state_shape_type state_shape;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _lidar_type;
  _lidar_type lidar;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _lidar_shape_type;
  _lidar_shape_type lidar_shape;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _direction_type;
  _direction_type direction;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _direction_shape_type;
  _direction_shape_type direction_shape;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _dynamic_obstacle_type;
  _dynamic_obstacle_type dynamic_obstacle;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _dynamic_obstacle_shape_type;
  _dynamic_obstacle_shape_type dynamic_obstacle_shape;





  typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPolicyInferenceRequest_

typedef ::navigation_runner::GetPolicyInferenceRequest_<std::allocator<void> > GetPolicyInferenceRequest;

typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceRequest > GetPolicyInferenceRequestPtr;
typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceRequest const> GetPolicyInferenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.state_shape == rhs.state_shape &&
    lhs.lidar == rhs.lidar &&
    lhs.lidar_shape == rhs.lidar_shape &&
    lhs.direction == rhs.direction &&
    lhs.direction_shape == rhs.direction_shape &&
    lhs.dynamic_obstacle == rhs.dynamic_obstacle &&
    lhs.dynamic_obstacle_shape == rhs.dynamic_obstacle_shape;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation_runner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eba1c092147ccc132b4778420f8a4a24";
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeba1c092147ccc13ULL;
  static const uint64_t static_value2 = 0x2b4778420f8a4a24ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_runner/GetPolicyInferenceRequest";
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] state\n"
"int32[] state_shape\n"
"float64[] lidar\n"
"int32[] lidar_shape\n"
"float64[] direction\n"
"int32[] direction_shape\n"
"float64[] dynamic_obstacle\n"
"int32[] dynamic_obstacle_shape\n"
;
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.state_shape);
      stream.next(m.lidar);
      stream.next(m.lidar_shape);
      stream.next(m.direction);
      stream.next(m.direction_shape);
      stream.next(m.dynamic_obstacle);
      stream.next(m.dynamic_obstacle_shape);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPolicyInferenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_runner::GetPolicyInferenceRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    if (v.state.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.state[i]);
    }
    if (v.state.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state_shape: ";
    if (v.state_shape.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.state_shape.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.state_shape[i]);
    }
    if (v.state_shape.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lidar: ";
    if (v.lidar.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lidar.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lidar[i]);
    }
    if (v.lidar.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lidar_shape: ";
    if (v.lidar_shape.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lidar_shape.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.lidar_shape[i]);
    }
    if (v.lidar_shape.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "direction: ";
    if (v.direction.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.direction.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.direction[i]);
    }
    if (v.direction.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "direction_shape: ";
    if (v.direction_shape.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.direction_shape.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.direction_shape[i]);
    }
    if (v.direction_shape.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_obstacle: ";
    if (v.dynamic_obstacle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dynamic_obstacle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.dynamic_obstacle[i]);
    }
    if (v.dynamic_obstacle.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_obstacle_shape: ";
    if (v.dynamic_obstacle_shape.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.dynamic_obstacle_shape.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.dynamic_obstacle_shape[i]);
    }
    if (v.dynamic_obstacle_shape.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCEREQUEST_H
