// Generated by gencpp from file navigation_runner/GetPolicyInference.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCE_H
#define NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCE_H

#include <ros/service_traits.h>


#include <navigation_runner/GetPolicyInferenceRequest.h>
#include <navigation_runner/GetPolicyInferenceResponse.h>


namespace navigation_runner
{

struct GetPolicyInference
{

typedef GetPolicyInferenceRequest Request;
typedef GetPolicyInferenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPolicyInference
} // namespace navigation_runner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_runner::GetPolicyInference > {
  static const char* value()
  {
    return "a4b6b43418ed234e9de75a5ccb110333";
  }

  static const char* value(const ::navigation_runner::GetPolicyInference&) { return value(); }
};

template<>
struct DataType< ::navigation_runner::GetPolicyInference > {
  static const char* value()
  {
    return "navigation_runner/GetPolicyInference";
  }

  static const char* value(const ::navigation_runner::GetPolicyInference&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_runner::GetPolicyInferenceRequest> should match
// service_traits::MD5Sum< ::navigation_runner::GetPolicyInference >
template<>
struct MD5Sum< ::navigation_runner::GetPolicyInferenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetPolicyInference >::value();
  }
  static const char* value(const ::navigation_runner::GetPolicyInferenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetPolicyInferenceRequest> should match
// service_traits::DataType< ::navigation_runner::GetPolicyInference >
template<>
struct DataType< ::navigation_runner::GetPolicyInferenceRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetPolicyInference >::value();
  }
  static const char* value(const ::navigation_runner::GetPolicyInferenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_runner::GetPolicyInferenceResponse> should match
// service_traits::MD5Sum< ::navigation_runner::GetPolicyInference >
template<>
struct MD5Sum< ::navigation_runner::GetPolicyInferenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetPolicyInference >::value();
  }
  static const char* value(const ::navigation_runner::GetPolicyInferenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetPolicyInferenceResponse> should match
// service_traits::DataType< ::navigation_runner::GetPolicyInference >
template<>
struct DataType< ::navigation_runner::GetPolicyInferenceResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetPolicyInference >::value();
  }
  static const char* value(const ::navigation_runner::GetPolicyInferenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCE_H
