// Generated by gencpp from file navigation_runner/GetPolicyInferenceResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCERESPONSE_H
#define NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_runner
{
template <class ContainerAllocator>
struct GetPolicyInferenceResponse_
{
  typedef GetPolicyInferenceResponse_<ContainerAllocator> Type;

  GetPolicyInferenceResponse_()
    : action()  {
    }
  GetPolicyInferenceResponse_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPolicyInferenceResponse_

typedef ::navigation_runner::GetPolicyInferenceResponse_<std::allocator<void> > GetPolicyInferenceResponse;

typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceResponse > GetPolicyInferenceResponsePtr;
typedef boost::shared_ptr< ::navigation_runner::GetPolicyInferenceResponse const> GetPolicyInferenceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator1> & lhs, const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator1> & lhs, const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation_runner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79f44d272f2ebe04451185b0dea57684";
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79f44d272f2ebe04ULL;
  static const uint64_t static_value2 = 0x451185b0dea57684ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_runner/GetPolicyInferenceResponse";
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] action\n"
;
  }

  static const char* value(const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPolicyInferenceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_runner::GetPolicyInferenceResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    if (v.action.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.action[i]);
    }
    if (v.action.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETPOLICYINFERENCERESPONSE_H
