// Generated by gencpp from file navigation_runner/GetSafeActionRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONREQUEST_H
#define NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace navigation_runner
{
template <class ContainerAllocator>
struct GetSafeActionRequest_
{
  typedef GetSafeActionRequest_<ContainerAllocator> Type;

  GetSafeActionRequest_()
    : agent_position()
    , agent_velocity()
    , agent_size(0.0)
    , obs_position()
    , obs_velocity()
    , obs_size()
    , laser_points()
    , laser_range(0.0)
    , laser_res(0.0)
    , max_velocity(0.0)
    , rl_velocity()  {
    }
  GetSafeActionRequest_(const ContainerAllocator& _alloc)
    : agent_position(_alloc)
    , agent_velocity(_alloc)
    , agent_size(0.0)
    , obs_position(_alloc)
    , obs_velocity(_alloc)
    , obs_size(_alloc)
    , laser_points(_alloc)
    , laser_range(0.0)
    , laser_res(0.0)
    , max_velocity(0.0)
    , rl_velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _agent_position_type;
  _agent_position_type agent_position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _agent_velocity_type;
  _agent_velocity_type agent_velocity;

   typedef double _agent_size_type;
  _agent_size_type agent_size;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _obs_position_type;
  _obs_position_type obs_position;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _obs_velocity_type;
  _obs_velocity_type obs_velocity;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _obs_size_type;
  _obs_size_type obs_size;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _laser_points_type;
  _laser_points_type laser_points;

   typedef double _laser_range_type;
  _laser_range_type laser_range;

   typedef double _laser_res_type;
  _laser_res_type laser_res;

   typedef double _max_velocity_type;
  _max_velocity_type max_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rl_velocity_type;
  _rl_velocity_type rl_velocity;





  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSafeActionRequest_

typedef ::navigation_runner::GetSafeActionRequest_<std::allocator<void> > GetSafeActionRequest;

typedef boost::shared_ptr< ::navigation_runner::GetSafeActionRequest > GetSafeActionRequestPtr;
typedef boost::shared_ptr< ::navigation_runner::GetSafeActionRequest const> GetSafeActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.agent_position == rhs.agent_position &&
    lhs.agent_velocity == rhs.agent_velocity &&
    lhs.agent_size == rhs.agent_size &&
    lhs.obs_position == rhs.obs_position &&
    lhs.obs_velocity == rhs.obs_velocity &&
    lhs.obs_size == rhs.obs_size &&
    lhs.laser_points == rhs.laser_points &&
    lhs.laser_range == rhs.laser_range &&
    lhs.laser_res == rhs.laser_res &&
    lhs.max_velocity == rhs.max_velocity &&
    lhs.rl_velocity == rhs.rl_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation_runner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf1c70d551fddbbb7abfbebc08b9923f";
  }

  static const char* value(const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf1c70d551fddbbbULL;
  static const uint64_t static_value2 = 0x7abfbebc08b9923fULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_runner/GetSafeActionRequest";
  }

  static const char* value(const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point agent_position\n"
"geometry_msgs/Vector3 agent_velocity\n"
"float64 agent_size\n"
"\n"
"# dynamic obstacles\n"
"geometry_msgs/Vector3[] obs_position\n"
"geometry_msgs/Vector3[] obs_velocity\n"
"geometry_msgs/Vector3[] obs_size\n"
"\n"
"# static obstacles\n"
"float64[] laser_points\n"
"float64 laser_range\n"
"float64 laser_res # use the larger one among horizonal and vertical\n"
"\n"
"float64 max_velocity\n"
"geometry_msgs/Vector3 rl_velocity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_position);
      stream.next(m.agent_velocity);
      stream.next(m.agent_size);
      stream.next(m.obs_position);
      stream.next(m.obs_velocity);
      stream.next(m.obs_size);
      stream.next(m.laser_points);
      stream.next(m.laser_range);
      stream.next(m.laser_res);
      stream.next(m.max_velocity);
      stream.next(m.rl_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSafeActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_runner::GetSafeActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_runner::GetSafeActionRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "agent_position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agent_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agent_size: ";
    Printer<double>::stream(s, indent + "  ", v.agent_size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obs_position: ";
    if (v.obs_position.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obs_position.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obs_position[i]);
    }
    if (v.obs_position.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obs_velocity: ";
    if (v.obs_velocity.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obs_velocity.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obs_velocity[i]);
    }
    if (v.obs_velocity.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obs_size: ";
    if (v.obs_size.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.obs_size.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.obs_size[i]);
    }
    if (v.obs_size.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "laser_points: ";
    if (v.laser_points.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.laser_points.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.laser_points[i]);
    }
    if (v.laser_points.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "laser_range: ";
    Printer<double>::stream(s, indent + "  ", v.laser_range);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "laser_res: ";
    Printer<double>::stream(s, indent + "  ", v.laser_res);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.max_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rl_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rl_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONREQUEST_H
