// Generated by gencpp from file navigation_runner/GetSafeActionResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONRESPONSE_H
#define NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace navigation_runner
{
template <class ContainerAllocator>
struct GetSafeActionResponse_
{
  typedef GetSafeActionResponse_<ContainerAllocator> Type;

  GetSafeActionResponse_()
    : safe_action()  {
    }
  GetSafeActionResponse_(const ContainerAllocator& _alloc)
    : safe_action(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _safe_action_type;
  _safe_action_type safe_action;





  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSafeActionResponse_

typedef ::navigation_runner::GetSafeActionResponse_<std::allocator<void> > GetSafeActionResponse;

typedef boost::shared_ptr< ::navigation_runner::GetSafeActionResponse > GetSafeActionResponsePtr;
typedef boost::shared_ptr< ::navigation_runner::GetSafeActionResponse const> GetSafeActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.safe_action == rhs.safe_action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation_runner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9504256e99d21a75b4954b17574a23";
  }

  static const char* value(const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9504256e99d21aULL;
  static const uint64_t static_value2 = 0x75b4954b17574a23ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_runner/GetSafeActionResponse";
  }

  static const char* value(const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 safe_action\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.safe_action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSafeActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_runner::GetSafeActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_runner::GetSafeActionResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "safe_action: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.safe_action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONRESPONSE_H
