// Generated by gencpp from file navigation_runner/GetSafeAction.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETSAFEACTION_H
#define NAVIGATION_RUNNER_MESSAGE_GETSAFEACTION_H

#include <ros/service_traits.h>


#include <navigation_runner/GetSafeActionRequest.h>
#include <navigation_runner/GetSafeActionResponse.h>


namespace navigation_runner
{

struct GetSafeAction
{

typedef GetSafeActionRequest Request;
typedef GetSafeActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSafeAction
} // namespace navigation_runner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_runner::GetSafeAction > {
  static const char* value()
  {
    return "54fa8c288cd542a68cd6fb86a87e59f8";
  }

  static const char* value(const ::navigation_runner::GetSafeAction&) { return value(); }
};

template<>
struct DataType< ::navigation_runner::GetSafeAction > {
  static const char* value()
  {
    return "navigation_runner/GetSafeAction";
  }

  static const char* value(const ::navigation_runner::GetSafeAction&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_runner::GetSafeActionRequest> should match
// service_traits::MD5Sum< ::navigation_runner::GetSafeAction >
template<>
struct MD5Sum< ::navigation_runner::GetSafeActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetSafeAction >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetSafeActionRequest> should match
// service_traits::DataType< ::navigation_runner::GetSafeAction >
template<>
struct DataType< ::navigation_runner::GetSafeActionRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetSafeAction >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_runner::GetSafeActionResponse> should match
// service_traits::MD5Sum< ::navigation_runner::GetSafeAction >
template<>
struct MD5Sum< ::navigation_runner::GetSafeActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetSafeAction >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetSafeActionResponse> should match
// service_traits::DataType< ::navigation_runner::GetSafeAction >
template<>
struct DataType< ::navigation_runner::GetSafeActionResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetSafeAction >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETSAFEACTION_H
