// Generated by gencpp from file navigation_runner/GetSafeActionMapRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAPREQUEST_H
#define NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace navigation_runner
{
template <class ContainerAllocator>
struct GetSafeActionMapRequest_
{
  typedef GetSafeActionMapRequest_<ContainerAllocator> Type;

  GetSafeActionMapRequest_()
    : agent_position()
    , agent_velocity()
    , agent_size(0.0)
    , dynamic_obs_position()
    , dynamic_obs_velocity()
    , dynamic_obs_size()
    , static_obs_position()
    , static_obs_size()
    , static_obs_angle()
    , max_velocity(0.0)
    , rl_velocity()  {
    }
  GetSafeActionMapRequest_(const ContainerAllocator& _alloc)
    : agent_position(_alloc)
    , agent_velocity(_alloc)
    , agent_size(0.0)
    , dynamic_obs_position(_alloc)
    , dynamic_obs_velocity(_alloc)
    , dynamic_obs_size(_alloc)
    , static_obs_position(_alloc)
    , static_obs_size(_alloc)
    , static_obs_angle(_alloc)
    , max_velocity(0.0)
    , rl_velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _agent_position_type;
  _agent_position_type agent_position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _agent_velocity_type;
  _agent_velocity_type agent_velocity;

   typedef double _agent_size_type;
  _agent_size_type agent_size;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _dynamic_obs_position_type;
  _dynamic_obs_position_type dynamic_obs_position;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _dynamic_obs_velocity_type;
  _dynamic_obs_velocity_type dynamic_obs_velocity;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _dynamic_obs_size_type;
  _dynamic_obs_size_type dynamic_obs_size;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _static_obs_position_type;
  _static_obs_position_type static_obs_position;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _static_obs_size_type;
  _static_obs_size_type static_obs_size;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _static_obs_angle_type;
  _static_obs_angle_type static_obs_angle;

   typedef double _max_velocity_type;
  _max_velocity_type max_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rl_velocity_type;
  _rl_velocity_type rl_velocity;





  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSafeActionMapRequest_

typedef ::navigation_runner::GetSafeActionMapRequest_<std::allocator<void> > GetSafeActionMapRequest;

typedef boost::shared_ptr< ::navigation_runner::GetSafeActionMapRequest > GetSafeActionMapRequestPtr;
typedef boost::shared_ptr< ::navigation_runner::GetSafeActionMapRequest const> GetSafeActionMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.agent_position == rhs.agent_position &&
    lhs.agent_velocity == rhs.agent_velocity &&
    lhs.agent_size == rhs.agent_size &&
    lhs.dynamic_obs_position == rhs.dynamic_obs_position &&
    lhs.dynamic_obs_velocity == rhs.dynamic_obs_velocity &&
    lhs.dynamic_obs_size == rhs.dynamic_obs_size &&
    lhs.static_obs_position == rhs.static_obs_position &&
    lhs.static_obs_size == rhs.static_obs_size &&
    lhs.static_obs_angle == rhs.static_obs_angle &&
    lhs.max_velocity == rhs.max_velocity &&
    lhs.rl_velocity == rhs.rl_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator1> & lhs, const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation_runner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "867ddf34cca17e53dbb05daa27a78640";
  }

  static const char* value(const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x867ddf34cca17e53ULL;
  static const uint64_t static_value2 = 0xdbb05daa27a78640ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_runner/GetSafeActionMapRequest";
  }

  static const char* value(const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point agent_position\n"
"geometry_msgs/Vector3 agent_velocity\n"
"float64 agent_size\n"
"\n"
"# dynamic obstacles\n"
"geometry_msgs/Vector3[] dynamic_obs_position\n"
"geometry_msgs/Vector3[] dynamic_obs_velocity\n"
"geometry_msgs/Vector3[] dynamic_obs_size\n"
"\n"
"# static obstacles\n"
"geometry_msgs/Vector3[] static_obs_position\n"
"geometry_msgs/Vector3[] static_obs_size\n"
"float64[] static_obs_angle\n"
"\n"
"float64 max_velocity\n"
"geometry_msgs/Vector3 rl_velocity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_position);
      stream.next(m.agent_velocity);
      stream.next(m.agent_size);
      stream.next(m.dynamic_obs_position);
      stream.next(m.dynamic_obs_velocity);
      stream.next(m.dynamic_obs_size);
      stream.next(m.static_obs_position);
      stream.next(m.static_obs_size);
      stream.next(m.static_obs_angle);
      stream.next(m.max_velocity);
      stream.next(m.rl_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSafeActionMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_runner::GetSafeActionMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "agent_position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agent_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agent_size: ";
    Printer<double>::stream(s, indent + "  ", v.agent_size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_obs_position: ";
    if (v.dynamic_obs_position.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.dynamic_obs_position.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.dynamic_obs_position[i]);
    }
    if (v.dynamic_obs_position.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_obs_velocity: ";
    if (v.dynamic_obs_velocity.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.dynamic_obs_velocity.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.dynamic_obs_velocity[i]);
    }
    if (v.dynamic_obs_velocity.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_obs_size: ";
    if (v.dynamic_obs_size.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.dynamic_obs_size.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.dynamic_obs_size[i]);
    }
    if (v.dynamic_obs_size.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "static_obs_position: ";
    if (v.static_obs_position.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.static_obs_position.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.static_obs_position[i]);
    }
    if (v.static_obs_position.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "static_obs_size: ";
    if (v.static_obs_size.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.static_obs_size.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.static_obs_size[i]);
    }
    if (v.static_obs_size.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "static_obs_angle: ";
    if (v.static_obs_angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.static_obs_angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.static_obs_angle[i]);
    }
    if (v.static_obs_angle.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.max_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rl_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rl_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAPREQUEST_H
