// Generated by gencpp from file navigation_runner/GetSafeActionMap.msg
// DO NOT EDIT!


#ifndef NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAP_H
#define NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAP_H

#include <ros/service_traits.h>


#include <navigation_runner/GetSafeActionMapRequest.h>
#include <navigation_runner/GetSafeActionMapResponse.h>


namespace navigation_runner
{

struct GetSafeActionMap
{

typedef GetSafeActionMapRequest Request;
typedef GetSafeActionMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSafeActionMap
} // namespace navigation_runner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_runner::GetSafeActionMap > {
  static const char* value()
  {
    return "4635b39c982fd59eaaa757b70b204f4c";
  }

  static const char* value(const ::navigation_runner::GetSafeActionMap&) { return value(); }
};

template<>
struct DataType< ::navigation_runner::GetSafeActionMap > {
  static const char* value()
  {
    return "navigation_runner/GetSafeActionMap";
  }

  static const char* value(const ::navigation_runner::GetSafeActionMap&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_runner::GetSafeActionMapRequest> should match
// service_traits::MD5Sum< ::navigation_runner::GetSafeActionMap >
template<>
struct MD5Sum< ::navigation_runner::GetSafeActionMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetSafeActionMap >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetSafeActionMapRequest> should match
// service_traits::DataType< ::navigation_runner::GetSafeActionMap >
template<>
struct DataType< ::navigation_runner::GetSafeActionMapRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetSafeActionMap >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_runner::GetSafeActionMapResponse> should match
// service_traits::MD5Sum< ::navigation_runner::GetSafeActionMap >
template<>
struct MD5Sum< ::navigation_runner::GetSafeActionMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_runner::GetSafeActionMap >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_runner::GetSafeActionMapResponse> should match
// service_traits::DataType< ::navigation_runner::GetSafeActionMap >
template<>
struct DataType< ::navigation_runner::GetSafeActionMapResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_runner::GetSafeActionMap >::value();
  }
  static const char* value(const ::navigation_runner::GetSafeActionMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_RUNNER_MESSAGE_GETSAFEACTIONMAP_H
