# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from navigation_runner/GetSafeActionMapRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class GetSafeActionMapRequest(genpy.Message):
  _md5sum = "867ddf34cca17e53dbb05daa27a78640"
  _type = "navigation_runner/GetSafeActionMapRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point agent_position
geometry_msgs/Vector3 agent_velocity
float64 agent_size

# dynamic obstacles
geometry_msgs/Vector3[] dynamic_obs_position
geometry_msgs/Vector3[] dynamic_obs_velocity
geometry_msgs/Vector3[] dynamic_obs_size

# static obstacles
geometry_msgs/Vector3[] static_obs_position
geometry_msgs/Vector3[] static_obs_size
float64[] static_obs_angle

float64 max_velocity
geometry_msgs/Vector3 rl_velocity

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['agent_position','agent_velocity','agent_size','dynamic_obs_position','dynamic_obs_velocity','dynamic_obs_size','static_obs_position','static_obs_size','static_obs_angle','max_velocity','rl_velocity']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Vector3','float64','geometry_msgs/Vector3[]','geometry_msgs/Vector3[]','geometry_msgs/Vector3[]','geometry_msgs/Vector3[]','geometry_msgs/Vector3[]','float64[]','float64','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       agent_position,agent_velocity,agent_size,dynamic_obs_position,dynamic_obs_velocity,dynamic_obs_size,static_obs_position,static_obs_size,static_obs_angle,max_velocity,rl_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetSafeActionMapRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.agent_position is None:
        self.agent_position = geometry_msgs.msg.Point()
      if self.agent_velocity is None:
        self.agent_velocity = geometry_msgs.msg.Vector3()
      if self.agent_size is None:
        self.agent_size = 0.
      if self.dynamic_obs_position is None:
        self.dynamic_obs_position = []
      if self.dynamic_obs_velocity is None:
        self.dynamic_obs_velocity = []
      if self.dynamic_obs_size is None:
        self.dynamic_obs_size = []
      if self.static_obs_position is None:
        self.static_obs_position = []
      if self.static_obs_size is None:
        self.static_obs_size = []
      if self.static_obs_angle is None:
        self.static_obs_angle = []
      if self.max_velocity is None:
        self.max_velocity = 0.
      if self.rl_velocity is None:
        self.rl_velocity = geometry_msgs.msg.Vector3()
    else:
      self.agent_position = geometry_msgs.msg.Point()
      self.agent_velocity = geometry_msgs.msg.Vector3()
      self.agent_size = 0.
      self.dynamic_obs_position = []
      self.dynamic_obs_velocity = []
      self.dynamic_obs_size = []
      self.static_obs_position = []
      self.static_obs_size = []
      self.static_obs_angle = []
      self.max_velocity = 0.
      self.rl_velocity = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.agent_position.x, _x.agent_position.y, _x.agent_position.z, _x.agent_velocity.x, _x.agent_velocity.y, _x.agent_velocity.z, _x.agent_size))
      length = len(self.dynamic_obs_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_position:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.dynamic_obs_velocity)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_velocity:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.dynamic_obs_size)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_size:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.static_obs_position:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_size)
      buff.write(_struct_I.pack(length))
      for val1 in self.static_obs_size:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.static_obs_angle))
      _x = self
      buff.write(_get_struct_4d().pack(_x.max_velocity, _x.rl_velocity.x, _x.rl_velocity.y, _x.rl_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.agent_position is None:
        self.agent_position = geometry_msgs.msg.Point()
      if self.agent_velocity is None:
        self.agent_velocity = geometry_msgs.msg.Vector3()
      if self.dynamic_obs_position is None:
        self.dynamic_obs_position = None
      if self.dynamic_obs_velocity is None:
        self.dynamic_obs_velocity = None
      if self.dynamic_obs_size is None:
        self.dynamic_obs_size = None
      if self.static_obs_position is None:
        self.static_obs_position = None
      if self.static_obs_size is None:
        self.static_obs_size = None
      if self.rl_velocity is None:
        self.rl_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.agent_position.x, _x.agent_position.y, _x.agent_position.z, _x.agent_velocity.x, _x.agent_velocity.y, _x.agent_velocity.z, _x.agent_size,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_position = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_position.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_velocity = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_velocity.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_size = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_size.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.static_obs_position = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.static_obs_position.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.static_obs_size = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.static_obs_size.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.static_obs_angle = s.unpack(str[start:end])
      _x = self
      start = end
      end += 32
      (_x.max_velocity, _x.rl_velocity.x, _x.rl_velocity.y, _x.rl_velocity.z,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.agent_position.x, _x.agent_position.y, _x.agent_position.z, _x.agent_velocity.x, _x.agent_velocity.y, _x.agent_velocity.z, _x.agent_size))
      length = len(self.dynamic_obs_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_position:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.dynamic_obs_velocity)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_velocity:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.dynamic_obs_size)
      buff.write(_struct_I.pack(length))
      for val1 in self.dynamic_obs_size:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.static_obs_position:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_size)
      buff.write(_struct_I.pack(length))
      for val1 in self.static_obs_size:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.static_obs_angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.static_obs_angle.tostring())
      _x = self
      buff.write(_get_struct_4d().pack(_x.max_velocity, _x.rl_velocity.x, _x.rl_velocity.y, _x.rl_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.agent_position is None:
        self.agent_position = geometry_msgs.msg.Point()
      if self.agent_velocity is None:
        self.agent_velocity = geometry_msgs.msg.Vector3()
      if self.dynamic_obs_position is None:
        self.dynamic_obs_position = None
      if self.dynamic_obs_velocity is None:
        self.dynamic_obs_velocity = None
      if self.dynamic_obs_size is None:
        self.dynamic_obs_size = None
      if self.static_obs_position is None:
        self.static_obs_position = None
      if self.static_obs_size is None:
        self.static_obs_size = None
      if self.rl_velocity is None:
        self.rl_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.agent_position.x, _x.agent_position.y, _x.agent_position.z, _x.agent_velocity.x, _x.agent_velocity.y, _x.agent_velocity.z, _x.agent_size,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_position = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_position.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_velocity = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_velocity.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dynamic_obs_size = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.dynamic_obs_size.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.static_obs_position = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.static_obs_position.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.static_obs_size = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Vector3()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.static_obs_size.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.static_obs_angle = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 32
      (_x.max_velocity, _x.rl_velocity.x, _x.rl_velocity.y, _x.rl_velocity.z,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from navigation_runner/GetSafeActionMapResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class GetSafeActionMapResponse(genpy.Message):
  _md5sum = "4b9504256e99d21a75b4954b17574a23"
  _type = "navigation_runner/GetSafeActionMapResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 safe_action

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['safe_action']
  _slot_types = ['geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       safe_action

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetSafeActionMapResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.safe_action is None:
        self.safe_action = geometry_msgs.msg.Vector3()
    else:
      self.safe_action = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.safe_action.x, _x.safe_action.y, _x.safe_action.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.safe_action is None:
        self.safe_action = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.safe_action.x, _x.safe_action.y, _x.safe_action.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d().pack(_x.safe_action.x, _x.safe_action.y, _x.safe_action.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.safe_action is None:
        self.safe_action = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.safe_action.x, _x.safe_action.y, _x.safe_action.z,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
class GetSafeActionMap(object):
  _type          = 'navigation_runner/GetSafeActionMap'
  _md5sum = '4635b39c982fd59eaaa757b70b204f4c'
  _request_class  = GetSafeActionMapRequest
  _response_class = GetSafeActionMapResponse
