(cl:in-package navigation_runner-srv)
(cl:export '(AGENT_POSITION-VAL
          AGENT_POSITION
          AGENT_VELOCITY-VAL
          AGENT_VELOCITY
          AGENT_SIZE-VAL
          AGENT_SIZE
          DYNAMIC_OBS_POSITION-VAL
          DYNAMIC_OBS_POSITION
          DYNAMIC_OBS_VELOCITY-VAL
          DYNAMIC_OBS_VELOCITY
          DYNAMIC_OBS_SIZE-VAL
          DYNAMIC_OBS_SIZE
          STATIC_OBS_POSITION-VAL
          STATIC_OBS_POSITION
          STATIC_OBS_SIZE-VAL
          STATIC_OBS_SIZE
          STATIC_OBS_ANGLE-VAL
          STATIC_OBS_ANGLE
          MAX_VELOCITY-VAL
          MAX_VELOCITY
          RL_VELOCITY-VAL
          RL_VELOCITY
          SAFE_ACTION-VAL
          SAFE_ACTION
))