// Generated by gencpp from file map_manager/GetStaticObstaclesRequest.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESREQUEST_H
#define MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_manager
{
template <class ContainerAllocator>
struct GetStaticObstaclesRequest_
{
  typedef GetStaticObstaclesRequest_<ContainerAllocator> Type;

  GetStaticObstaclesRequest_()
    {
    }
  GetStaticObstaclesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetStaticObstaclesRequest_

typedef ::map_manager::GetStaticObstaclesRequest_<std::allocator<void> > GetStaticObstaclesRequest;

typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesRequest > GetStaticObstaclesRequestPtr;
typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesRequest const> GetStaticObstaclesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace map_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/GetStaticObstaclesRequest";
  }

  static const char* value(const ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStaticObstaclesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::map_manager::GetStaticObstaclesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESREQUEST_H
