// Generated by gencpp from file map_manager/GetStaticObstaclesResponse.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESRESPONSE_H
#define MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace map_manager
{
template <class ContainerAllocator>
struct GetStaticObstaclesResponse_
{
  typedef GetStaticObstaclesResponse_<ContainerAllocator> Type;

  GetStaticObstaclesResponse_()
    : position()
    , size()
    , angle()  {
    }
  GetStaticObstaclesResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , size(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _position_type;
  _position_type position;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _size_type;
  _size_type size;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStaticObstaclesResponse_

typedef ::map_manager::GetStaticObstaclesResponse_<std::allocator<void> > GetStaticObstaclesResponse;

typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesResponse > GetStaticObstaclesResponsePtr;
typedef boost::shared_ptr< ::map_manager::GetStaticObstaclesResponse const> GetStaticObstaclesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator1> & lhs, const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.size == rhs.size &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator1> & lhs, const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10afeb58fe82a6ef3c941519f4670020";
  }

  static const char* value(const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10afeb58fe82a6efULL;
  static const uint64_t static_value2 = 0x3c941519f4670020ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_manager/GetStaticObstaclesResponse";
  }

  static const char* value(const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] position\n"
"geometry_msgs/Vector3[] size\n"
"float64[] angle\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.size);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStaticObstaclesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_manager::GetStaticObstaclesResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    if (v.position.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.position[i]);
    }
    if (v.position.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    if (v.size.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.size.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.size[i]);
    }
    if (v.size.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    if (v.angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.angle[i]);
    }
    if (v.angle.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETSTATICOBSTACLESRESPONSE_H
