// Generated by gencpp from file map_manager/GetStaticObstacles.msg
// DO NOT EDIT!


#ifndef MAP_MANAGER_MESSAGE_GETSTATICOBSTACLES_H
#define MAP_MANAGER_MESSAGE_GETSTATICOBSTACLES_H

#include <ros/service_traits.h>


#include <map_manager/GetStaticObstaclesRequest.h>
#include <map_manager/GetStaticObstaclesResponse.h>


namespace map_manager
{

struct GetStaticObstacles
{

typedef GetStaticObstaclesRequest Request;
typedef GetStaticObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStaticObstacles
} // namespace map_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_manager::GetStaticObstacles > {
  static const char* value()
  {
    return "10afeb58fe82a6ef3c941519f4670020";
  }

  static const char* value(const ::map_manager::GetStaticObstacles&) { return value(); }
};

template<>
struct DataType< ::map_manager::GetStaticObstacles > {
  static const char* value()
  {
    return "map_manager/GetStaticObstacles";
  }

  static const char* value(const ::map_manager::GetStaticObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::map_manager::GetStaticObstaclesRequest> should match
// service_traits::MD5Sum< ::map_manager::GetStaticObstacles >
template<>
struct MD5Sum< ::map_manager::GetStaticObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetStaticObstacles >::value();
  }
  static const char* value(const ::map_manager::GetStaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetStaticObstaclesRequest> should match
// service_traits::DataType< ::map_manager::GetStaticObstacles >
template<>
struct DataType< ::map_manager::GetStaticObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetStaticObstacles >::value();
  }
  static const char* value(const ::map_manager::GetStaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_manager::GetStaticObstaclesResponse> should match
// service_traits::MD5Sum< ::map_manager::GetStaticObstacles >
template<>
struct MD5Sum< ::map_manager::GetStaticObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_manager::GetStaticObstacles >::value();
  }
  static const char* value(const ::map_manager::GetStaticObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_manager::GetStaticObstaclesResponse> should match
// service_traits::DataType< ::map_manager::GetStaticObstacles >
template<>
struct DataType< ::map_manager::GetStaticObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::map_manager::GetStaticObstacles >::value();
  }
  static const char* value(const ::map_manager::GetStaticObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MANAGER_MESSAGE_GETSTATICOBSTACLES_H
