(cl:defpackage map_manager-srv
  (:use )
  (:export
   "CHECKPOSCOLLISION"
   "<CHECKPOSCOLLISION-REQUEST>"
   "CHECKPOSCOLLISION-REQUEST"
   "<CHECKPOSCOLLISION-RESPONSE>"
   "CHECKPOSCOLLISION-RESPONSE"
   "GETSTATICOBSTACLES"
   "<GETSTATICOBSTACLES-REQUEST>"
   "GETSTATICOBSTACLES-REQUEST"
   "<GETSTATICOBSTACLES-RESPONSE>"
   "GETSTATICOBSTACLES-RESPONSE"
   "RAYCAST"
   "<RAYCAST-REQUEST>"
   "RAYCAST-REQUEST"
   "<RAYCAST-RESPONSE>"
   "RAYCAST-RESPONSE"
  ))

